#!/usr/bin/env bash
# clco installer — GitHub Copilot-backed Claude Code wrapper.
#   curl -fsSL https://raw.githubusercontent.com/semanticist21/clco/main/install.sh | bash
set -euo pipefail

REPO="https://github.com/semanticist21/clco.git"
CLCO_DIR="${CLCO_DIR:-$HOME/.local/share/clco}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mError:\033[0m %s\n' "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || fail "git is required - please install it first"

# --- Bun (auto-install when missing) ---------------------------------------
if ! command -v bun >/dev/null 2>&1; then
  log "Bun not found - installing it with the official script"
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
  command -v bun >/dev/null 2>&1 || fail "Could not verify the Bun install - reopen your terminal and retry"
fi

# --- Source ------------------------------------------------------------------
if [ -d "$CLCO_DIR/.git" ]; then
  log "Updating the existing install: $CLCO_DIR"
  # Pre-rename clones carry a stale origin — retarget before pulling.
  CURRENT_URL="$(git -C "$CLCO_DIR" remote get-url origin 2>/dev/null || true)"
  case "$CURRENT_URL" in
    *semanticist21/clco.git) ;;
    https://*|git@github.com:*)
      [ -n "$CURRENT_URL" ] && git -C "$CLCO_DIR" remote set-url origin "$REPO"
      ;;
  esac
  git -C "$CLCO_DIR" pull --ff-only >/dev/null 2>&1 || fail "Update failed - run git pull in $CLCO_DIR to see why"
else
  [ -e "$CLCO_DIR" ] && fail "$CLCO_DIR already exists and is not a git repo - remove it and retry"
  log "Cloning into $CLCO_DIR"
  git clone --depth 1 "$REPO" "$CLCO_DIR"
fi

log "Installing dependencies (bun install)"
(cd "$CLCO_DIR" && bun install --frozen-lockfile >/dev/null 2>&1) \
  || (cd "$CLCO_DIR" && bun install >/dev/null 2>&1) \
  || { log "bun install failed - full output:"; (cd "$CLCO_DIR" && bun install) || fail "bun install failed"; }

# --- claude CLI (required by clco; offer to install) -------------------------
CLAUDE_WARN="Install it later with: curl -fsSL https://claude.ai/install.sh | bash"
if command -v claude >/dev/null 2>&1; then
  log "Found the claude CLI"
else
  log "The claude CLI is missing (clco needs it)"
  INSTALL_CLAUDE=n
  if [ -e /dev/tty ]; then
    printf 'Install it now? [y/N] '
    answer=n
    read -r answer < /dev/tty || answer=n
    case "$answer" in y|Y|yes|Yes) INSTALL_CLAUDE=y ;; esac
  fi
  if [ "$INSTALL_CLAUDE" = y ]; then
    log "Installing the claude CLI (official script)"
    curl -fsSL https://claude.ai/install.sh | bash
    export PATH="$HOME/.local/bin:$PATH"
    command -v claude >/dev/null 2>&1 \
      || log "! Could not verify the claude install - reopen your terminal and check. $CLAUDE_WARN"
  else
    log "! Skipped - clco needs the claude CLI before it can run. $CLAUDE_WARN"
  fi
fi

# --- Launcher ----------------------------------------------------------------
# Generated by a script the repo owns, so `clco update` refreshes it too.
bash "$CLCO_DIR/scripts/write-launcher.sh" "$CLCO_DIR" "$BIN_DIR"



case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) printf '\033[1;33mNote:\033[0m %s is not on your PATH. Add it to ~/.zshrc or similar:\n  export PATH="%s:$PATH"\n' "$BIN_DIR" "$BIN_DIR" ;;
esac

log "Installed: $BIN_DIR/clco"
printf '\nGetting started:\n  clco          first run: GitHub device login, pick a model, launch claude\n  clco setup    set your startup defaults\n  clco --help   full usage\n\nUninstall:\n  curl -fsSL https://raw.githubusercontent.com/semanticist21/clco/main/uninstall.sh | bash\n'
