#!/usr/bin/env bash
# Writes the clco launcher. Lives here rather than inline in install.sh so
# `clco update` can refresh it too — a launcher baked at install time used to
# stay stale forever, since update only ran `git pull` + `bun install`.
#
# Usage: write-launcher.sh <app-dir> <bin-dir> [bun-path]
set -euo pipefail

CLCO_DIR="${1:?app dir required}"
BIN_DIR="${2:?bin dir required}"
BUN_BIN="${3:-$(command -v bun)}"
[ -n "$BUN_BIN" ] || { echo "bun not found" >&2; exit 1; }

# Bump when the launcher body changes; clco compares it to warn about a stale
# launcher that predates a feature.
LAUNCHER_VERSION=2

mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/clco" <<LAUNCHER
#!/bin/sh
# clco launcher v$LAUNCHER_VERSION (generated by scripts/write-launcher.sh)
CLCO_APP_DIR="$CLCO_DIR"
CLCO_LAUNCHER_VERSION=$LAUNCHER_VERSION
export CLCO_APP_DIR CLCO_LAUNCHER_VERSION

# Corporate TLS: clco adds a CA to the OS trust store itself, per request, via
# CLCO_CA_BUNDLE — see src/tls.ts. Nothing to set here; NODE_USE_SYSTEM_CA is
# a no-op on bun, whose default trust set already merges the system roots.

# bun strips a leading "--" before scripts see it — translate it into a
# sentinel that cli.ts understands as "everything after is claude's".
if [ "\$1" = "--" ]; then
  shift
  set -- "__clco_passthrough__" "\$@"
fi
exec "$BUN_BIN" run "$CLCO_DIR/src/cli.ts" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/clco"
